Make defaults section customizable
mrlesmithjr/ansible-rsyslog pull request #7
Opened 2018-11-08 20:06 UTC by pillarsdotnet

This allows customizing the `/etc/rsyslog.d/50-defaults.conf` file through variables rather than by hand-editing the template or the target file itself.

2018-11-09 03:26 UTC, mrlesmithjr requested changes

2018-11-09 03:26 UTC, mrlesmithjr commented on defaults/main.yml
> +  - name: '/var/log/news/news.notice
missing ending `'`

2018-11-11 03:48 UTC, pillarsdotnet commented on defaults/main.yml
> +  - name: '/var/log/news/news.notice
Corrected.

2018-11-15 13:57 UTC, mrlesmithjr commented on defaults/main.yml
> +  - name: '/var/log/news/news.notice
Perfect

2018-11-15 13:57 UTC, mrlesmithjr approved these changes

2018-11-15 13:57 UTC, merged

2018-11-15 13:57 UTC, mrlesmithjr commented
@pillarsdotnet Merged